version: '3.8'

services:

  SC-1:
    container_name: SC-1
    hostname: SC-1
    command: bash -c "./setup.sh"
    image: local/go-cpsv
    cap_add:
      - NET_ADMIN
    volumes:
      - ./topology/producer.go:/home/opensaf/demo.go
      - ./topology/setup.sh:/home/opensaf/setup.sh
      - ./sharedfs:/etc/opensaf/sharedfs
    networks:
      privnet:
        aliases:
          - gocpsv.sc1.tw
 
  SC-2:
    container_name: SC-2
    hostname: SC-2
    command: bash -c "./setup.sh"
    image: local/go-cpsv
    cap_add:
      - NET_ADMIN
    volumes:
      - ./topology/consumer.go:/home/opensaf/demo.go
      - ./topology/setup.sh:/home/opensaf/setup.sh
      - ./sharedfs:/etc/opensaf/sharedfs
    networks:
      privnet:
        aliases:
          - gocpsv.sc2.tw
    depends_on:
     - SC-1

  PL-3:
    container_name: PL-3
    hostname: PL-3
    command: bash -c "./setup.sh"
    image: local/go-cpsv
    cap_add:
      - NET_ADMIN
    volumes:
      - ./topology/json_example.go:/home/opensaf/demo.go
      - ./topology/setup_pl.sh:/home/opensaf/setup.sh
      - ./sharedfs:/etc/opensaf/sharedfs
    networks:
      privnet:
        aliases:
          - gocpsv.pl1.tw
    depends_on:
     - SC-2

networks:
  privnet:
    ipam:
      driver: default
    driver_opts:
      com.docker.network.bridge.name: br-gocpsv

volumes:
  sharedfs: