version: '3.8'

services:
  SC-1:
    container_name: SC-1
    command: bash -c "cd GO-CPSV && go run ./producer.go"
    image: local/go-cpsv
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - gocpsv.sc1.tw

  SC-2:
    container_name: SC-2
    command: bash -c "cd GO-CPSV && go run ./consumer.go"
    image: local/go-cpsv
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - gocpsv.sc2.tw

  db:
    container_name: mongodb
    image: mongo
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      privnet:
        aliases:
          - db

networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.80.0.0/24
    driver_opts:
      com.docker.network.bridge.name: br-gocpsv

volumes:
  dbdata: